[package]
name = "tg-keeper"
version = "0.1.0"
edition = "2021"

[dependencies]
grammers-client = "0.7"
grammers-session = "0.7"
tokio = { version = "1.44", features = ["full"] }
anyhow = "1.0"
env_logger = "0.10"
log = "0.4"
config = "0.13"
chrono = "0.4"
mime2ext = "0.1"
