# Telegram API credentials
# You can obtain these at https://my.telegram.org/apps
tg_api_id = 123456  # Replace with your API ID
tg_api_hash = "0123456789abcdef0123456789abcdef" # Replace with your API hash
